### ISSUE TITLE
TypeError: alias_nb_pages() missing 1 required positional argument: 'alias'

### ISSUE THREAD

**Issue by carlosal1015** [ismet55555/exam-terminal#12]
**Describe the bug**

When I finished the exam and I select Save Result PDF, then I look this error

```console
Traceback (most recent call last):
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/bin/exam-terminal", line 8, in <module>
    sys.exit(main())
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/exam_terminal/__main__.py", line 97, in main
    exitcode = exam_terminal.exam_terminal(exam_file_contents)
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/exam_terminal/exam_terminal.py", line 45, in exam_terminal
    exam.export_results_to_pdf()
  File "/home/carlosal1015/Git_Projects/Python/ManimCE/exercises/.venv/lib/python3.9/site-packages/exam_terminal/ExamTerminal.py", line 1088, in export_results_to_pdf
    pdf.alias_nb_pages()
TypeError: alias_nb_pages() missing 1 required positional argument: 'alias'
```

**To Reproduce**
1. Install with poetry `exam-terminal = "0.2.5"` and use python 3.9.1.
2. Create a Test.yml.
2. Execute `exam-terminal -e Text.yml`. Do the quiz and select Save Result PDF.
4. See the above error

**Expected behavior**
Create a PDF with `ghostscript`, `pdflatex`?

**Screenshots**
![image](https://user-images.githubusercontent.com/21283014/107451276-f5114600-6b14-11eb-8a84-857ac1ea3daf.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - exam-terminal's version: 0.2.5.

**Comment by ismet55555** [comment]
Hey, thank you for submitting this!

I went ahead and removed that one line.  It is only to set up the page and does not effect the general function of generating the PDF file.
https://github.com/ismet55555/exam-terminal/pull/13

Documentation for that one line of code:
https://pyfpdf.readthedocs.io/en/latest/reference/alias_nb_pages/index.html

In any case you want to tinker with the code or run it locally, I also included a quick getting started guide:
https://github.com/ismet55555/exam-terminal/blob/master/dev_stuff/getting_started.md

PyPI should be updated to 0.2.6 now

**Comment by carlosal1015** [comment]
Hi @ismet55555. I tried the last version and all works great. Thanks for do it.

```console
certifi       2020.12.5 Python package for providing Mozilla's CA Bundle.
chardet       4.0.0     Universal encoding detector for Python 2 and 3
click         7.1.2     Composable command line interface toolkit
exam-terminal 0.2.6     A terminal-based exam, text, or survey tool for educators and learners
fpdf2         2.3.4     Simple PDF generation for Python
idna          2.10      Internationalized Domain Names in Applications (IDNA)
pillow        8.2.0     Python Imaging Library (Fork)
pyyaml        5.4.1     YAML parser and emitter for Python
requests      2.25.1    Python HTTP for Humans.
urllib3       1.26.4    HTTP library with thread-safe connection pooling, file post, and more.
```

**Comment by carlosal1015** [comment]
Hi @ismet55555, it will be great if in the [next releases](https://pypi.org/project/exam-terminal/#files)will have file `requirements.txt` or `License` inside `tar.gz`.

**Comment by ismet55555** [comment]
Hey, yeah no problem, I can try that.
Curious, any reason you need it inside the `tar.gz` release file?

**Comment by carlosal1015** [comment]
Thanks @ismet55555, I would like to [submit the package]([`exam-terminal`](https://gitlab.com/dune-archiso/pkgbuilds/dune/-/raw/main/PKGBUILDS/exam-terminal/PKGBUILD)) to the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository) like [`python-fpdf2`](https://aur.archlinux.org/packages/python-fpdf2).

Then, to achieve the installation, the user compile from source, that is, have the file `requirements.txt`, which is called by `setup.py`.
