### ISSUE TITLE
Reduce the requirement of window size

### ISSUE THREAD

**Issue by GrimPixel** [ismet55555/exam-terminal#68]
**Describe the bug**
It can't run it as I have two horizontal panels (which are called “task bar” on Windows) on Linux, unless it's in full screen mode.

**To Reproduce**
1. Install Arch Linux
2. Run the program

**Expected behavior**
Little to no restrictions on the window size.

**Comment by ismet55555** [comment]
Sorry for the delay. Let me investigate.
